### PR TITLE
configure options to mitigate V26 crashes

### PR DESCRIPTION
**Pull request by sparklyballs**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]
	

##  Thanks, team linuxserver.io

+ as per https://github.com/ejurgensen/forked-daapd/issues/502#issuecomment-370264870
+ ffmpeg latest version in edge was still producing crashes so went with updating configure ac file and options

### CODE REVIEW

**Comment by ejurgensen** [comment]
I wouldn't recommend pulling configure.ac from the master branch at build time, because configure.ac in the master branch may change at any time and become incompatible with release 26.0.

**Comment by sparklyballs** [comment]
would it be possible in that case to release a 26.1 version containing current compatible configure ac ? 

then because we build from your latest release we only then need the configure option --disable-avcodecsend

**Comment by ejurgensen** [comment]
Can't you just apply the commit you want as a patch before building?

I'll make a 26.1 if I find a serious bug in 26.0, but so far this looks like a ffmpeg problem.

**Comment by sparklyballs** [comment]
@ejurgensen i've amended the PR to pull specific commit for the configure file

**Review by tobbenb — APPROVED** [review]

**Pull request merged**
