### PR TITLE
Fix the Build

### PR DESCRIPTION
**Pull request by BernsteinA**
This supersedes https://github.com/linuxserver/docker-daapd/pull/31
See also https://github.com/ejurgensen/forked-daapd/issues/871

### CODE REVIEW

**Comment by aptalca** [comment]
Build failing
```
checking for library containing antlr3BaseRecognizerNew...... no
configure: error: in `/tmp/source/forked-daapd':
configure: error: Function antlr3BaseRecognizerNew in libantlr3c not found.
Install ANTLR3 C runtime in the default include path, or alternatively set
library specific environment variables ANTLR3C_CFLAGS
and ANTLR3C_LIBS.
See `config.log' for more details
```

**Comment by kinglouie** [comment]
@BernsteinA I think this does not supersede #31 I only got the build working if I use this image containing the libantlr build from source https://github.com/chme/docker-daapd/tree/fixbuild.

The alpine version bump just fixes the websocket issue.

**Comment by BernsteinA** [comment]
@kinglouie oh shoot. I misunderstood your comment, thought that updating alpine fixed both.

**Comment by teejo75** [comment]
You need to add libantlr3c as well as libantlr3c-dev to the build packages. This allowed the image to build for me.

https://github.com/linuxserver/docker-daapd/blob/57615bebc1613b6e33a64c05b5c6924907ab6e2e/Dockerfile#L45

However, now there is the issue where daapd just restarts constantly. * When you access the web interface.

**Comment by kinglouie** [comment]
My build based on https://github.com/chme/docker-daapd/tree/fixbuild with the additional change of the alpine version works flawlessly with high usage. Didn't crash since deployment a few weeks ago so I would suggest using that antlr3c fixed istead of using the ```libantlr3c-dev``` package.

@BernsteinA do you want to update this PR or should I open a new one?

**Comment by nicx** [comment]
@kinglouie do you have your build on docker hub? I would be really happy to test it ;)

**Comment by BernsteinA** [comment]
@kinglouie @teejo75 I've updated this PR. Seems good on x64 here, will try ARM when I get home

**Comment by BernsteinA** [comment]
@thelamer I think we're back up and running

**Comment by aptalca** [comment]
It seems to keep crashing and restarting when I open the webpage

You can test with `docker run -d --rm --name daapd --net=host lspipepr/daapd`
Check the logs with `docker logs daapd -f` and visit the url

**Comment by teejo75** [comment]
The build where libantl3r is built from source works perfectly, I tested it last night updating the alpine to use 3.11 as @kinglouie said.

**Comment by BernsteinA** [comment]
ok yeah it's crashing / restarting for me too. I guess we have to build antlr from source after all

**Comment by thelamer** [comment]
Stop the blind commits you can test building images locally on x86, the instructions are in all of our readmes

**Comment by nicx** [comment]
any news to this? will it be merged?

**Review by quentinb69 — APPROVED** [review]

**Comment by aptalca** [comment]
Is it working? Tested?

**Comment by BernsteinA** [comment]
I’m running it on armhf with no problems that I’ve noticed

**Review by aptalca — APPROVED** [review]

**Comment by aptalca** [comment]
@BernsteinA thanks for all the work

**Pull request merged**
