### PR TITLE
Changes to build against owntone-server release

### LINKED ISSUE #50: New build of owntone failing on jenkins
Hi @BernsteinA 
Just a heads up, the builds for the new version of Owntone are failing on jenkins: https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-daapd/activity

I'm gonna pause the external trigger for now. Let me know when you get a chance to look into it and we'll enable the triggers after it's fixed.

Thanks

### PR DESCRIPTION
**Pull request by dhutchison**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-daapd/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

Changes paths in the build & links to refer to the new name of the project, owntone-server. As-is the main branch of this project does not build. 

closes #50

## Benefits of this PR and context:

Fixes #50. 

## How Has This Been Tested?

Verified that x86 image built and I could install & run the container.

### CODE REVIEW

**Comment by BernsteinA** [comment]
This looks good to me.
Can I get a quick ok from you @aptalca before I merge?

**Comment by aptalca** [comment]
@BernsteinA lgtm

**Review by BernsteinA — APPROVED** [review]

**Review by BernsteinA — APPROVED** [review]

**Comment by BernsteinA** [comment]
Ok so I don't know who has write permissions to merge this now...
cc @Roxedus

**Comment by Roxedus** [comment]
I got you

**Comment by BernsteinA** [comment]
I don't know where to put this, but we should add a notice somewhere that pulling the latest image will create a new settings file `owntone.conf` and will not read from your existing `forked-daapd.conf`
Could be a very disruptive change for many users...

**Comment by BernsteinA** [comment]
Maybe we should roll back this pr, and change the docker image name before applying it again?

**Pull request merged**
