### PR TITLE
Updated config name to owntone

### PR DESCRIPTION
**Pull request by Marko298**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-daapd/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

Updated config name to owntone.conf

### CODE REVIEW

**Comment by Roxedus** [comment]
Same changes as #51

**Comment by Marko298** [comment]
my fault, sorry

**Comment by BernsteinA** [comment]
thanks @Marko298 @Roxedus I am working on getting the other PR merged asap

**Comment by Marko298** [comment]
Thank you!

**Pull request closed without merging**
