### PR TITLE
Add support to specify spotify connect device name

### LINKED ISSUE #68: Allow specifying spotify connect display name
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

## Desired Behavior

Allow for the Spotify connect display name to be set with an environment variable

## Current Behavior

The spotify connect display name is hardcoded as `forked-daapd`:

https://github.com/linuxserver/docker-daapd/blob/3faff0bf300dcbee7dd30b4dec24745d12432e7f/root/etc/services.d/librespot/run#L2

### PR DESCRIPTION
**Pull request by nickw444**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-daapd/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

This PR enables users to optionally specify the display name that their OwnTone container should identify as in the Spotify Connect menu.

Closes https://github.com/linuxserver/docker-daapd/issues/68

It also updates the default name from `forked-daapd` to `OwnTone` to be in-line with the new naming of the project. 

| Without `SPOTIFY_CONNECT_NAME` specified | With `SPOTIFY_CONNECT_NAME=MultiRoom` specified |
|---|---|
| IMG_4417 | IMG_4418 |

## Benefits of this PR and context:

This provides a more family-friendly (non technical) user interface for family members who wish to utilise the OwnTone instance for multi-room streaming without needing to know that "forked-daapd" means "mutli room" - The IT administrator can now give the Spotify Connect instance a friendlier name, like "Multi Room".

## How Has This Been Tested?

Yes - I have run the container under Portainer with `--net=host` and confirmed both the override and fallback (`OwnTone`) behavior to work.

## Source / References:

N/A

### CODE REVIEW

**Comment by BernsteinA** [comment]
Awesome, thanks for the PR!
As the de facto maintainer I’m happy to merge this if it passes the automated build, but do any of you use Spotify and can do a quick test?
@bverhagen @aptalca @thelamer

**Comment by nickw444** [comment]
Hey @BernsteinA would you be opposed to adding some additional envvars to control librespot? Specifically I'd like to add `bitrate` since the [default is 160](https://github.com/librespot-org/librespot/wiki/Options) when not specified, but I'd like to have playback at 320. (My workaround for this is to have a separate "high quality" spotify connect receiver container running Spocon, but would be great to integrate this into the one container)

**Comment by thespad** [comment]
We would prefer if you're going to do that to have a general "librespot CLI args" env and pass that as a single object rather than adding half a dozen new env options.

**Comment by nickw444** [comment]
Stale but not forgotten! I will be back soon

**Comment by nickw444** [comment]
Not stale - waiting for review.

**Comment by bverhagen** [comment]
@BernsteinA : I do no longer use this feature (and even tried removing it at some point). The UX was not great, as the pipe forwards data, but not control, causing misalignment between the states librespot and owntone thought they were in. The feature is not in my way either, so obviously, if other's use it, by all means they can.

**Comment by nickw444** [comment]
Not stale - waiting for a review.

**Comment by nickw444** [comment]
Not stale - waiting for a review.

**Comment by nickw444** [comment]
Not stale - waiting for a review.

**Comment by BernsteinA** [comment]
Well, I think it’s just me here, so you might have to do what I did and
become a maintainer too, then you can approve it yourself :)

**Comment by nickw444** [comment]
I wouldn't be opposed to that

image

**Comment by mcchas** [comment]
bump.
this PR works fine for me

**Comment by nickw444** [comment]
Not stale

**Comment by daydy16** [comment]
@Roxedus @aptalca any change to get this PR merged?

Thx 🙏

**Review by kminhtri — APPROVED** [review]
LGTM

**Review by kminhtri — APPROVED** [review]

**Comment by Roxedus** [comment]
> @Roxedus @aptalca any change to get this PR merged?
> 
> Thx 🙏

I have no way to test this.

**Comment by kminhtri** [comment]
up

**Review by homerr — DISMISSED** [review]
Happy with this, would appreciate a 2nd opinion though, and will test locally to see if it works as intended. Update to follow

**Comment by nickw444** [comment]
I no longer use this image.

**Comment by mcchas** [comment]
> I no longer use this image. 

Ah.. we were so close

Turns out you could just change the name in the config file.

**Comment by fwump38** [comment]
@mcchas how can you specify it in the config?

**Comment by mcchas** [comment]
> @mcchas how can you specify it in the config?

I may be incorrect and haven't tested it (I just use this branch), but noticed this setting can be changed  in `config.toml ` as `deviceName`

image

**Comment by nickw444** [comment]
Just to circle back, and elaborate on my comment above:

I ended up moving to a more flexible solution that is tailored to my needs. I run a Proxmox host, with a CT container that runs docker/docker compose. I have a compose file that runs:

* Official OwnTone image (`streamer`)
* Official OwnTone image (`library`)
* Spocon

I have a shared volume between Spocon and Owntone streamer instance to share the audio pipe. I can then configure spocon to my liking. I use watchtower to keep the containers up to date.

The reason for two OwnTone instances is that my music library is very large, which causes incredibly long bootup times and really laggy web UI and slow response to starting Spocon pipe, so I have a dedicate instance for Spocon multi-room streaming.

**Pull request closed without merging**
